name: Lint with Ruff (flake-based)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-flake:
    runs-on: macos-14

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@cebd211ec2008b83bda8fb0b21c3c072f004fe04 # v31

      - name: Run Ruff via nix develop shell
        run: |
          nix develop --command ruff check .

