name: Lint with Ruff (flake-based)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Run Ruff
    runs-on: macos-14

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - name: Run Ruff via nix develop shell
        run: |
          nix develop --command ruff check .

