name: Lint with Ruff (flake-based)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-flake:
    runs-on: macos-14

    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31

      - name: Run Ruff via nix develop shell
        run: |
          nix develop --command ruff check .

